import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
// import "./styles/globals.css";

import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { fontAladin, fontJakarta } from "@/styles/font";

// const inter = Inter({ subsets: ["latin"] });

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          fontSans.variable,
          fontJakarta.variable,
          fontAladin.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
